name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ruby:2.7.0

    steps:
      - uses: actions/checkout@v1
      - run: ruby main.rb
      # - run: gem install bundler --no-document
      # - run: bundle config set deployment 'true'
      # - run: bundle install --jobs 4 --retry 3
      # - run: bundle exec rake
