name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ruby:2.7.0

    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          gem install bundler --no-document
          bundle config set deployment 'true'
          bundle install --jobs 4 --retry 3
      - name: lint
        run: bundle exec rubocop
      - name: rspec
        run: bundle exec rspec
